struct Position {
    var horizontal: Int = 0
    var depth: Int = 0
    var aim: Int = 0

    var value: Int { horizontal * depth }

    mutating func move(_ movement: Movement) {
        switch movement.direction {
        case .forward:
            horizontal += movement.value
        case .up:
            depth -= movement.value
        case .down:
            depth += movement.value
        }
    }

    mutating func move2(_ movement: Movement) {
        switch movement.direction {
        case .forward:
            horizontal += movement.value
            depth += aim * movement.value
        case .up:
            aim -= movement.value
        case .down:
            aim += movement.value
        }
    }
}

enum Direction {
    case forward, up, down
}

struct Movement {
    let direction: Direction
    let value: Int

    init(direction: Direction, value: Int) {
        self.direction = direction
        self.value = value
    }

    init?(line: Substring) {
        var text = line.drop(while: { $0.isWhitespace })

        let removeAmount: Int
        let direction: Direction
        if text.hasPrefix("forward") {
            direction = .forward
            removeAmount = 7
        } else if text.hasPrefix("down") {
            direction = .down
            removeAmount = 4
        } else if text.hasPrefix("up") {
            direction = .up
            removeAmount = 2
        } else {
            return nil
        }
        text.removeFirst(removeAmount)
        while text.first?.isWhitespace == true {
            text.removeFirst()
        }
        let numText = text.prefix(while: { $0.isNumber })
        guard
            !numText.isEmpty,
            let value = Int(numText)
        else { return nil }
        self.init(direction: direction, value: value)
    }

    static func == (lhs: Movement, rhs: Movement) -> Bool {
        return lhs.direction == rhs.direction &&
        lhs.value == rhs.value
    }

    static func parseLines() throws -> [Movement] {
        try Day2.lines().map {
            try Movement(line: $0).orThrow(AdventError("could not parse line"))
        }
    }
}

enum Day2: Day {
    static let day: Int = 2

    static func solution1() throws -> String {
        try String(
            Movement.parseLines()
                .reduce(into: Position()) { position, movement in
                    position.move(movement)
                }.depth
        )
    }

    static func solution2() throws -> String {
        try String(
            Movement.parseLines()
                .reduce(into: Position()) { position, movement in
                    position.move2(movement)
                }.depth
        )
    }

    static let input: String = """
        forward 8
        forward 3
        down 8
        down 2
        up 1
        up 4
        down 9
        forward 3
        forward 4
        forward 5
        forward 1
        forward 1
        up 8
        forward 2
        forward 9
        down 2
        forward 8
        down 5
        down 3
        down 8
        up 1
        forward 1
        down 8
        up 7
        down 8
        down 9
        down 4
        down 7
        forward 7
        forward 9
        down 2
        down 5
        forward 1
        down 1
        forward 2
        up 8
        down 8
        forward 2
        up 5
        down 6
        down 5
        down 2
        forward 5
        forward 4
        forward 6
        down 4
        up 1
        down 8
        down 7
        down 3
        down 4
        down 5
        forward 7
        down 3
        down 3
        forward 3
        down 2
        up 8
        up 8
        forward 2
        down 8
        down 8
        forward 3
        forward 9
        forward 3
        forward 2
        down 9
        down 3
        forward 4
        forward 1
        down 7
        forward 5
        up 2
        down 6
        up 4
        down 2
        up 5
        forward 6
        down 6
        down 1
        forward 5
        forward 4
        up 8
        up 5
        forward 2
        down 5
        down 4
        up 1
        forward 9
        up 5
        up 5
        forward 3
        down 6
        forward 7
        down 2
        forward 1
        forward 4
        forward 4
        down 2
        down 6
        down 3
        down 1
        forward 1
        down 8
        forward 2
        down 1
        down 2
        forward 6
        forward 1
        forward 7
        forward 2
        down 2
        up 6
        up 2
        forward 7
        down 6
        down 1
        forward 5
        forward 3
        forward 1
        down 3
        up 1
        forward 3
        forward 1
        down 2
        down 5
        up 8
        down 8
        forward 3
        down 9
        forward 8
        down 8
        down 5
        forward 2
        up 1
        down 3
        up 3
        down 5
        down 7
        down 8
        down 8
        down 1
        forward 9
        up 4
        up 4
        down 5
        forward 6
        forward 1
        up 6
        forward 5
        up 6
        forward 1
        forward 9
        down 3
        down 8
        forward 6
        forward 6
        up 1
        down 6
        forward 2
        down 7
        down 2
        forward 4
        up 4
        up 2
        forward 8
        up 6
        down 8
        up 3
        down 5
        down 3
        forward 3
        down 8
        up 4
        up 5
        down 1
        down 7
        down 7
        forward 6
        up 6
        down 1
        forward 7
        down 2
        up 7
        up 3
        forward 9
        down 3
        up 4
        up 1
        forward 8
        down 4
        forward 9
        forward 8
        down 4
        down 3
        down 1
        forward 8
        up 7
        down 3
        up 5
        down 3
        down 9
        down 9
        up 9
        down 9
        up 4
        down 5
        down 5
        forward 8
        forward 1
        up 3
        down 9
        down 8
        forward 2
        forward 1
        up 6
        down 3
        forward 1
        up 6
        forward 9
        forward 3
        forward 3
        down 2
        down 7
        forward 1
        up 9
        up 3
        forward 1
        forward 2
        forward 7
        forward 8
        forward 2
        forward 3
        forward 1
        forward 7
        down 1
        up 7
        up 3
        forward 3
        forward 9
        down 7
        down 3
        forward 2
        forward 8
        up 1
        forward 2
        forward 3
        up 2
        down 1
        down 9
        down 4
        up 3
        forward 3
        down 6
        down 1
        forward 2
        down 8
        forward 3
        forward 9
        forward 1
        forward 6
        forward 5
        down 5
        forward 2
        up 7
        up 7
        down 8
        forward 9
        up 1
        up 5
        up 8
        forward 5
        forward 2
        down 5
        up 5
        down 3
        forward 6
        down 9
        down 7
        forward 2
        forward 8
        forward 3
        down 7
        down 8
        forward 9
        down 3
        down 3
        forward 1
        forward 4
        down 2
        forward 1
        forward 3
        forward 5
        down 9
        up 3
        down 5
        forward 8
        forward 3
        down 5
        forward 3
        forward 7
        down 3
        forward 8
        down 1
        down 3
        down 4
        down 2
        forward 8
        down 2
        forward 5
        down 2
        up 2
        forward 8
        forward 9
        forward 3
        forward 2
        forward 3
        down 2
        forward 5
        down 1
        down 9
        up 1
        down 6
        forward 2
        up 1
        forward 6
        down 2
        forward 2
        forward 1
        forward 4
        forward 4
        forward 9
        forward 2
        down 5
        forward 9
        forward 1
        forward 7
        forward 1
        down 7
        forward 7
        down 4
        down 8
        down 8
        down 1
        forward 4
        down 5
        up 3
        down 5
        forward 6
        down 6
        down 4
        down 9
        down 4
        down 5
        forward 7
        up 4
        forward 6
        down 9
        down 5
        down 5
        up 2
        forward 8
        up 5
        down 1
        down 2
        up 6
        down 7
        forward 7
        up 5
        forward 4
        up 5
        down 3
        up 7
        forward 4
        down 4
        down 5
        down 7
        down 3
        down 9
        up 8
        down 9
        forward 6
        forward 2
        forward 2
        up 8
        up 2
        down 4
        down 4
        up 7
        up 9
        forward 2
        forward 8
        forward 4
        up 8
        forward 8
        up 2
        down 3
        forward 9
        down 1
        down 7
        forward 4
        down 2
        up 6
        up 6
        down 9
        forward 6
        forward 9
        down 3
        forward 8
        up 1
        down 5
        forward 1
        down 6
        up 8
        forward 2
        up 7
        forward 5
        down 5
        up 3
        forward 2
        forward 1
        forward 4
        down 6
        up 9
        forward 9
        down 8
        forward 2
        down 1
        down 3
        forward 2
        forward 9
        up 1
        forward 9
        down 4
        forward 2
        forward 7
        forward 1
        up 2
        up 2
        down 9
        forward 3
        forward 2
        down 6
        up 8
        down 4
        forward 8
        up 9
        up 6
        down 5
        up 1
        down 9
        down 2
        down 1
        up 8
        down 1
        forward 3
        down 7
        down 7
        forward 8
        down 4
        forward 1
        forward 4
        forward 5
        down 8
        down 2
        down 9
        up 5
        down 8
        down 8
        down 3
        forward 2
        down 5
        up 5
        down 1
        down 2
        forward 9
        down 7
        down 7
        down 1
        down 6
        up 6
        up 7
        down 1
        down 3
        down 2
        down 5
        down 9
        down 4
        down 5
        forward 1
        up 7
        down 7
        forward 6
        forward 4
        down 3
        forward 3
        forward 6
        forward 7
        down 3
        forward 1
        down 6
        down 8
        forward 3
        up 3
        forward 4
        forward 3
        down 6
        up 7
        forward 8
        forward 4
        down 7
        down 6
        down 8
        forward 9
        down 6
        down 5
        up 4
        down 6
        down 8
        down 5
        up 4
        forward 2
        forward 8
        forward 9
        down 2
        forward 5
        down 9
        down 2
        down 7
        forward 2
        down 2
        up 7
        down 2
        up 5
        forward 3
        down 8
        forward 3
        forward 8
        up 3
        down 6
        down 1
        forward 2
        up 7
        down 8
        forward 8
        down 2
        down 3
        down 5
        forward 4
        forward 5
        down 2
        forward 2
        down 5
        down 9
        forward 4
        forward 3
        forward 2
        down 9
        forward 2
        forward 9
        down 5
        down 9
        down 6
        down 6
        down 3
        down 1
        down 7
        forward 7
        forward 2
        up 9
        forward 4
        up 7
        forward 3
        down 2
        up 8
        up 3
        down 4
        up 9
        forward 1
        down 1
        forward 4
        up 4
        forward 4
        up 8
        forward 7
        down 3
        forward 1
        up 3
        up 1
        up 2
        down 3
        forward 5
        down 6
        down 1
        down 2
        forward 2
        down 3
        up 1
        forward 4
        down 2
        forward 8
        forward 3
        forward 7
        forward 7
        down 5
        down 7
        forward 8
        up 2
        down 6
        forward 1
        down 4
        forward 5
        forward 8
        forward 9
        forward 7
        down 1
        down 3
        down 1
        down 2
        forward 3
        up 3
        down 7
        forward 9
        forward 2
        up 8
        up 6
        up 3
        down 5
        forward 8
        down 8
        down 6
        forward 4
        down 2
        down 8
        forward 8
        up 7
        up 4
        up 5
        down 4
        up 6
        forward 2
        forward 9
        down 9
        forward 6
        down 5
        down 7
        forward 5
        up 5
        forward 2
        up 7
        up 3
        down 8
        forward 8
        forward 3
        down 2
        down 5
        forward 4
        down 8
        forward 5
        forward 4
        down 9
        forward 1
        down 4
        up 5
        forward 5
        down 1
        forward 4
        down 4
        forward 4
        down 8
        up 5
        up 4
        up 9
        forward 2
        forward 3
        down 3
        forward 2
        down 6
        down 6
        down 5
        forward 8
        forward 3
        up 1
        down 9
        down 4
        down 1
        up 4
        forward 2
        forward 3
        down 4
        up 4
        forward 5
        forward 2
        up 2
        forward 4
        down 2
        down 3
        down 6
        up 2
        forward 8
        forward 9
        forward 1
        down 1
        up 7
        up 4
        forward 2
        forward 4
        forward 2
        forward 8
        down 9
        down 5
        down 1
        down 1
        down 6
        forward 1
        up 6
        down 4
        down 9
        down 2
        down 2
        down 5
        up 6
        forward 4
        forward 1
        forward 2
        forward 8
        forward 2
        down 6
        forward 1
        down 8
        down 1
        forward 2
        forward 3
        down 9
        down 7
        down 5
        up 1
        forward 1
        down 5
        down 4
        forward 8
        down 9
        up 7
        forward 6
        forward 2
        forward 8
        down 9
        down 1
        up 5
        down 5
        down 3
        forward 6
        forward 5
        forward 2
        forward 6
        up 4
        forward 1
        down 9
        forward 5
        up 1
        down 5
        down 6
        forward 8
        down 4
        up 9
        down 6
        down 9
        down 7
        down 3
        forward 7
        down 5
        up 6
        forward 3
        up 4
        down 5
        up 5
        up 9
        forward 9
        forward 8
        down 9
        forward 9
        down 2
        forward 5
        forward 5
        forward 9
        down 3
        up 8
        down 7
        up 9
        forward 8
        forward 8
        down 1
        down 5
        down 4
        up 8
        forward 4
        forward 7
        down 2
        down 7
        down 6
        down 9
        down 7
        forward 5
        forward 7
        forward 5
        forward 2
        forward 7
        up 2
        down 8
        down 9
        down 5
        down 9
        forward 5
        forward 8
        forward 9
        up 5
        down 9
        down 7
        forward 4
        down 6
        up 5
        up 8
        down 3
        down 2
        up 7
        forward 9
        down 3
        down 2
        down 7
        down 4
        up 6
        up 4
        down 7
        down 4
        forward 5
        forward 6
        up 6
        down 7
        down 9
        down 9
        down 6
        forward 8
        forward 3
        forward 5
        up 1
        up 8
        forward 4
        forward 6
        down 5
        down 4
        forward 5
        forward 9
        down 4
        up 3
        up 8
        down 7
        up 8
        forward 5
        forward 3
        up 4
        up 9
        forward 6
        down 1
        up 6
        down 5
        down 4
        down 3
        down 8
        up 1
        down 1
        up 8
        up 8
        down 6
        forward 4
        forward 9
        down 4
        down 7
        forward 9
        forward 8
        up 6
        down 9
        up 3
        down 8
        forward 4
        forward 6
        forward 9
        up 7
        down 2
        forward 2
        forward 1
        forward 5
        up 9
        up 7
        up 5
        forward 4
        forward 5
        forward 4
        up 5
        forward 4
        up 6
        down 5
        up 2
        forward 5
        forward 5
        down 9
        forward 7
        down 9
        up 4
        up 9
        forward 6
        forward 7
        down 2
        forward 4
        down 9
        down 6
        forward 1
        forward 7
        up 3
        up 3
        down 6
        up 6
        up 2
        up 3
        forward 7
        up 4
        forward 1
        down 1
        forward 2
        forward 4
        down 1
        down 8
        forward 5
        forward 8
        up 7
        down 3
        forward 3
        forward 6
        down 8
        down 7
        up 9
        forward 3
        up 1
        down 8
        forward 4
        down 9
        forward 3
        forward 8
        down 4
        forward 4
        forward 1
        up 6
        down 1
        down 7
        forward 8
        down 9
        down 8
        down 7
        forward 5
        up 6
        forward 5
        up 1
        down 3
        down 7
        down 4
        forward 6
        down 4
        down 7
        up 9
        down 6
        down 7
        up 3
        up 8
        forward 3
        forward 1
        forward 5
        down 5
        forward 5
        down 1
        forward 9
        up 5
        forward 4
        down 1
        down 8
        up 1
        up 3
        up 8
        down 3
        down 5
        up 7
        forward 4
        down 7
        forward 9
        forward 7
        forward 9
        down 9
        forward 3
        forward 6
        up 3
        forward 4
        forward 4
        """
}
